### ISSUE TITLE
Dockers should have proper Label Schema labels

### ISSUE THREAD

**Issue by kmehant** [scorelab/OpenDF#89]
This repos has a Dockerfile but it does not contain any Label Schema labels.  Following are the lables we have to have on our Dockers. 
- [x] `name` 
- [x] `description` Shoud be on user's perspective.
- [x] `url` Should be SCoRe website
- [x] `vcs-url` Should point to GitHub repo
- [x] `vcs-ref`
- [x] `vendor` Shoudl be "SCoRe Lab"
- [x] `version`
- [x] `schema-version`

**Comment by kmehant** [comment]
@agentmilindu Would like to work on this issue.

**Comment by kmehant** [comment]
@agentmilindu Kindly review the commit, before i create a pull request.

https://github.com/kmehant/OpenDF/blob/master/Dockerfile

**Comment by agentmilindu** [comment]
Wonderful job! Let's set  the `org.label-schema.schema-version` to `1.0`. 
Like `org.label-schema.schema-version = "1.0"`

**Comment by kmehant** [comment]
@agentmilindu Thank you for pointing it out, i addressed your changes :D

**Comment by agentmilindu** [comment]
Nice! Merged. 

Fixed with #90.

**Comment by kmehant** [comment]
@agentmilindu Thank you so much for the merge :)
